name: iv_project_web_app
description: "In Vite Project Web App"
publish_to: 'none'
version: 0.1.5

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  iv_project_model:
    path: ../iv_project_model

  iv_project_web_data:
    path: ../iv_project_web_data

  iv_project_core:
    path: ../iv_project_core
  
  iv_project_widget_core:
    path: ../iv_project_widget_core

  iv_project_invitation_theme:
    path: ../iv_project_invitation_theme
  
  quick_dev_sdk:
    path: ../quick_dev_sdk

  go_router: ^17.0.0
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  http: ^1.5.0
  file_saver: ^0.3.1
  file_picker: ^10.3.6
  excel: ^4.0.6
  url_launcher: ^6.3.2
  mobile_scanner: ^7.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/templates/formulir_tamu_undangan.xlsx
