name: iv_project_web_app
description: "In Vite Project Web App"
publish_to: 'none'
version: 0.1.5

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  iv_project_model:
    git:
      url: https://github.com/faequl96/iv_project_model.git
      ref: 0.1.1

  iv_project_web_data:
    git:
      url: https://github.com/faequl96/iv_project_web_data.git
      ref: 0.0.1+3

  iv_project_core:
    git:
      url: https://github.com/faequl96/iv_project_core.git
      ref: 0.0.9+1

  iv_project_widget_core:
    git:
      url: https://github.com/faequl96/iv_project_widget_core.git
      ref: 0.0.2+4
  
  iv_project_invitation_theme:
    git:
      url: https://github.com/faequl96/iv_project_invitation_theme.git
      ref: 0.2.0+6
  
  quick_dev_sdk:
    git:
      url: https://github.com/faequl96/quick_dev_sdk.git
      ref: 0.0.8+2

  go_router: ^17.0.0
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  http: ^1.5.0
  file_saver: ^0.3.1
  file_picker: ^10.3.6
  excel: ^4.0.6
  url_launcher: ^6.3.2
  mobile_scanner: ^7.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/templates/formulir_tamu_undangan.xlsx
